---
- name: Converge
  hosts: all
  vars:
    atl_product_family: "crowd"
    atl_product_edition: "crowd"
    atl_product_user: "crowd"
    atl_download_format: "tarball"
    ansible_ec2_placement_region: 'us-east-1'
    
  roles:
    - role: linux_common
    - role: product_common
    - role: product_install
