---
- name: Converge
  hosts: all
  vars:
    atl_product_family: "stash"
    atl_product_edition: "bitbucket"
    atl_product_user: "bitbucket"
    ansible_ec2_placement_region: 'us-east-1'

    atl_product_home: "{{ atl_shared_mountpoint }}/{{ atl_product_edition }}"
  roles:
    - role: linux_common
    - role: product_common
    - role: product_install
