---

- name: Add Adoptium repo and install Eclipse Temurin JDK if necessary on Amazon Linux
  block:

    - name: Add Adoptium yum repository
      yum_repository:
        name: Adoptium
        file: adoptium
        description: Adoptium Repo
        baseurl: "https://packages.adoptium.net/artifactory/rpm/amazonlinux/{{ ansible_distribution_version }}/{{ ansible_architecture }}"
        gpgkey: https://packages.adoptium.net/artifactory/api/gpg/key/public
        gpgcheck: yes
        state: present

    - name: Install Eclipse Temurin JDK
      yum:
        name: "temurin-{{ java_major_version }}-jdk"
        state: present

    - name: Ensure common JDK symlink exists
      alternatives:
        link: "/usr/lib/jvm/java"
        name: "java_sdk"
        path: "/usr/lib/jvm/temurin-{{ java_major_version }}-jdk"
        priority: 99

  when: atl_use_system_jdk
  tags:
    - runtime_pkg

- name: Install other base packages on Amazon Linux
  yum:
    name:
      - dejavu-fonts-common  # Required by the installer
